# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_version = "202107.28.0"
  config.vm.network "private_network", ip: "172.16.33.21"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "linux-2"
    vb.memory = 2048
    vb.cpus = 1
  end
end
