# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/sql-server"
  config.vm.box_version = "2019.0.2012"
  config.vm.network "private_network", ip: "172.16.33.30"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "windows-1"
    vb.memory = 4096
    vb.cpus = 2
  end
  config.vm.synced_folder "./", "/vagrant"
end
